export const IDOX_COUNCIL_DOMAIN_MAP: Record<string, string> = {
  Hackney: "publicaccess.hackney.gov.uk",
  Islington: "publicaccess.islington.gov.uk",
  "Tower Hamlets": "development.towerhamlets.gov.uk",
  Newham: "pa.newham.gov.uk",
  Southwark: "planning.southwark.gov.uk",
  Lambeth: "planning.lambeth.gov.uk",
  Lewisham: "planning.lewisham.gov.uk",
  Greenwich: "www2.greenwich.gov.uk",
  Westminster: "idoxpa.westminster.gov.uk",
  "Hammersmith and Fulham": "public-access.lbhf.gov.uk",
  "Kensington and Chelsea": "publicaccess.rbkc.gov.uk",
  Haringey: "www.planningservices.haringey.gov.uk",
  Barnet: "publicaccess.barnet.gov.uk",
  Enfield: "planningandbuildingcontrol.enfield.gov.uk",
  "Waltham Forest": "planning.walthamforest.gov.uk",
  Redbridge: "publicaccess.redbridge.gov.uk",
  Havering: "development.havering.gov.uk",
  Bexley: "pa.bexley.gov.uk",
  Bromley: "searchapplications.bromley.gov.uk",
  Croydon: "publicaccess3.croydon.gov.uk",
  Sutton: "planningregister.sutton.gov.uk",
  Kingston: "publicaccess.kingston.gov.uk",
  Hounslow: "planning.hounslow.gov.uk",
};
